### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = np.mean(a, axis=0)

In [13]:
mean_a

array([2. , 8.4])

### Задание 2

In [37]:
a_centered = a - mean_a

In [38]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [39]:
# Скалярное произведение векторов / число наблюдений
a_centered_sp = (b[:, 0] @ b[:, 1]) / b.shape[0]

In [40]:
a_centered_sp

1.6